name: Update Submodules

on:
  push:
    branches:
      - main # or your default branch

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: Anton12xx/template # Format: Organization/Repository
          event-type: update-template
          