name: Update Submodules

on:
  push:
    branches:
      - main # or your default branch

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
        
          repository: Anton123xx/newTemplate # Format: Organization/Repository
          event-type: update-template
          